services:
  app1:
    build: .
    ports:
      - "5001:5000"
    networks:
      - rede_mensagens
    volumes:
      - volume_mensagens:/data
    environment:
      - APP_NAME=app1
      - PEERS=app2,app3

  app2:
    build: .
    ports:
      - "5002:5000"
    networks:
      - rede_mensagens
    volumes:
      - volume_mensagens:/data
    environment:
      - APP_NAME=app2
      - PEERS=app1,app3

  app3:
    build: .
    ports:
      - "5003:5000"
    networks:
      - rede_mensagens
    volumes:
      - volume_mensagens:/data
    environment:
      - APP_NAME=app3
      - PEERS=app1,app2

networks:
  rede_mensagens:
    driver: bridge

volumes:
  volume_mensagens:
